import 'package:flutter/material.dart';
import '/package.dart';

Map<String, Widget Function(BuildContext)> routes = <String, WidgetBuilder>{
  Auth.route: (context) => const Auth(),
  Onboarding.route: (context) => const Onboarding(),
  Otp.route: (context) => const Otp(),
  ChangePassword.route: (context) => const ChangePassword(),
  ForgotPassword.route: (context) => const ForgotPassword(),
  CnicBack.route: (context) => const CnicBack(),
  CnicFront.route: (context) => const CnicFront(),
  DriverLicense.route: (context) => const DriverLicense(),
  DriverRegistration.route: (context) => const DriverRegistration(),
  ProfilePhoto.route: (context) => const ProfilePhoto(),
  TermsConditions.route: (context) => const TermsConditions(),
  VehicleRegistration.route: (context) => const VehicleRegistration(),
  Signin.route: (context) => const Signin(),
  Signup.route: (context) => const Signup(),
  Splash.route: (context) => const Splash(),
  Permissions.route: (context) => const Permissions(),
  Status.route: (context) => const Status(),
  Become.route: (context) => const Become(),

  //Rider
  Rider.route: (context) => const Rider(),
  RiderHome.route: (context) => const RiderHome(),
  NowTime.route: (context) => const NowTime(),
  WhereToLocation.route: (context) => const WhereToLocation(),
  Notifications.route: (context) => const Notifications(),
  Messages.route: (context) => const Messages(),
  Sos.route: (context) => const Sos(),
  Passenger.route: (context) => const Passenger(),
  ListDisplay.route: (context) => const ListDisplay(),
  Profile.route: (context) => const Profile(),
  ProfileUpdate.route: (context) => const ProfileUpdate(),
  Payment.route: (context) => const Payment(),
  CreditDebit.route: (context) => const CreditDebit(),
  ApplePay.route: (context) => const ApplePay(),
  Cash.route: (context) => const Cash(),
  PasswordUpdate.route: (context) => const PasswordUpdate(),
  Search.route: (context) => const Search(),
  Invite.route: (context) => const Invite(),
  InviteViaEmail.route: (context) => const InviteViaEmail(),
  InviteViaMobile.route: (context) => const InviteViaMobile(),
  InviteViaQR.route: (context) => const InviteViaQR(),
  Setting.route: (context) => const Setting(),
  // //Driver
  Driver.route: (context) => const Driver(),
  DriverHome.route: (context) => const DriverHome(),
  Pickups.route: (context) => const Pickups(),
  Stopovers.route: (context) => const Stopovers(),
  Calendar.route: (context) => const Calendar(),
  DropOff.route: (context) => const DropOff(),
  Routes.route: (context) => const Routes(),
  GoneSchedule.route: (context) => const GoneSchedule(),
  PickupLocation.route: (context) => const PickupLocation(),
  PassengersBook.route: (context) => const PassengersBook(),
  Passengers.route: (context) => const Passengers(),
  PhoneVerify.route: (context) => const PhoneVerify(),
  PricePassengers.route: (context) => const PricePassengers(),
  ReturnRide.route: (context) => const ReturnRide(),
  DropoffLocation.route: (context) => const DropoffLocation(),
  Sure.route: (context) => const Sure(),
};
